import Head from "next/head";
import Art from "@/components/home/Art";
import Nft from "@/components/home/Nft";
import MapRoad from "@/components/home/MapRoad";
import MockData from "@/components/data/MockData";
import { useState } from "react";
import Cards from "@/components/home/Cards";

export default function Home() {
    const [item] = useState(MockData);
    return (
      <>
        <Head>
          <title>Meta - NFT</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Art/>
          <Cards item={item}/>
          <Nft/>
          <MapRoad/>
        </main>
      </>
    );
  }
  